name: neo4j_build
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - black=19.10b0
  - neo4j-python-driver=4.1
  - pandas=1.1.3
  - environs=8.0.0
  - loguru=0.5.3
  - scipy=1.5.2
  - pandas-profiling=2.8.0
  - pytest
  - pytest-xdist
  - pydantic
  - pyyaml
  - pip=20.2.4
  - pip:
    - biomart==0.9.2
    - wget
    - snakemake>=5.27
